# change the followings to match your Github username and repo name
baseurl: "/reme-web" # the name of your github repo
url: "https://remehamweb.github.io/" # the url of your github pages

# site information used in page title, meta data etc.
title: "瑞美食品"
description: Reme Ham

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Reme Ham
author-bio: Taiwan Company # change to false to hide
author-image: 280.jpg # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: https://instagram.com/
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Made by Jack"
footer-msg-link: "" 

# google analytics
google-analytics: 

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
